import{VERSION,configFromSearch,makeGame,accepts,describe,resultShare,challengeURL}from'./engine.mjs';
const $=id=>document.getElementById(id);
const copy={
 en:{nav:'HUMAN INTELLIGENCE CLUB',dailyLabel:'A DAILY EGO CHECK FOR A ROBOT',confident:'CONFIDENT.',wrong:'STILL WRONG.',intro:'Six labels. One mistake. A robot that refuses to admit it. Catch its bad call in five quick rounds.',start:'HUMBLE THE BOT',practice:'Practice a random challenge',free:'FREE TO PLAY',time:'ABOUT 90 SECONDS',account:'NO ACCOUNT',speech:'I HAVE NEVER\nBEEN WRONG.*',footnote:'* according to the bot.',ego:'EGO: UNLIMITED',step1:'READ THE RULE.',step1text:'The rule is visible. No guessing what we are thinking.',step2:'FIND ITS MISTAKE.',step2text:'Exactly one of the six labels breaks that rule.',step3:'COLLECT AN EXCUSE.',step3text:'Five rounds. A shareable score. A bruised robot ego.',home:'← Home',roundTag:'FIND THE ONE WRONG LABEL',rule:'THE ACTUAL RULE',otherwise:'Otherwise, REJECT. The bot labels are shown below.',next:'NEXT ROUND',noTimer:'No countdown. Read carefully. This is a game, not an intelligence test.',debrief:'HUMAN INTELLIGENCE REPORT',copy:'COPY CHALLENGE ↗',card:'MAKE MY CARD ↓',again:'Another practice round →',shareLabel:'YOUR SCORE + THE SAME CHALLENGE FOR A FRIEND',saveCard:'SAVE CARD ↓',saveHint:'If downloading is unavailable, save the preview image using your browser.',scoreNote:'Scores are self-reported and stored on this device. There is no global leaderboard or prize.',aboutTitle:'A LITTLE LESS HYPE.\nA LITTLE MORE HUMAN.',aboutText:'A free, open-source logic game with a fictional robot. Rules and jokes are scripted. No live AI model, wallet connection, token sale, or paid advantage.',privacy:'Scores stay in your browser. Hosting providers may log requests.',source:'SOURCE ↗'},
 zh:{nav:'人类智力俱乐部',dailyLabel:'给机器人的每日自信来一记重拳',confident:'自信满满。',wrong:'照样出错。',intro:'六个判断，一个错误。还有一个死不认错的机器人。用五个小关卡，揭穿它的嘴硬。',start:'让它认错',practice:'先来一局随机练习',free:'免费玩',time:'大约 90 秒',account:'无需账号',speech:'我从来\n没有错过。*',footnote:'* 据它自己说。',ego:'自我感觉：无限良好',step1:'先读规则。',step1text:'规则明明白白，不需要猜出题人的心思。',step2:'揪出错误。',step2text:'六个标签中，有且只有一个违反规则。',step3:'收获嘴硬。',step3text:'五个关卡，一张挑战卡，一个破防的机器人。',home:'← 首页',roundTag:'找到唯一判错的标签',rule:'真正的规则',otherwise:'其他情况一律不通过。下方展示机器人的判断。',next:'下一关',noTimer:'没有倒计时，慢慢想。这是游戏，不是智力测验。',debrief:'人类智力报告',copy:'复制挑战 ↗',card:'生成战绩卡 ↓',again:'再来一局随机练习 →',shareLabel:'你的成绩，以及给朋友的同题挑战链接',saveCard:'保存战绩卡 ↓',saveHint:'若无法下载，可通过浏览器保存上方图片。',scoreNote:'分数由本机记录，可自行修改；没有全球排行榜或奖品。',aboutTitle:'少一点吹嘘。\n多一点人味。',aboutText:'一个免费开源的逻辑游戏，机器人是虚构角色。规则与笑话均预先编写，没有实时 AI 模型、钱包连接、代币售卖或付费优势。',privacy:'成绩只保存在浏览器。托管服务商可能记录访问请求。',source:'查看源码 ↗'}
};
const colors={en:{pink:'PINK',blue:'BLUE',lime:'LIME'},zh:{pink:'粉色',blue:'蓝色',lime:'绿色'}},shapes={en:{circle:'CIRCLE',square:'SQUARE',triangle:'TRIANGLE'},zh:{circle:'圆形',square:'正方形',triangle:'三角形'}},colorValues={pink:'#eca9bd',blue:'#a4bfdc',lime:'#c5e096'};
const excuses={en:['My confidence score disagrees.','This is a user perception issue.','I was testing whether you were paying attention.','Your eyes are using an outdated version.','I meant the other definition of correct.'],zh:['我的自信分数不同意。','这是用户感知问题。','我在测试你有没有认真看。','你的眼睛版本太旧了。','我说的是另一种“正确”。']};
function storageGet(key){try{return localStorage.getItem(key);}catch{return null;}}
function storageSet(key,value){try{localStorage.setItem(key,value);}catch{}}
let lang=storageGet('vwb-language')==='zh'?'zh':'en',config=configFromSearch(location.search),rounds=[],hits=[],selected=[],index=0,phase='landing',runNumber=0;
const msg=(en,zh)=>lang==='zh'?zh:en;
function prior(){try{const r=JSON.parse(storageGet('vwb-v1-'+config.key));return r&&Array.isArray(r.hits)&&r.hits.length===5&&r.hits.every(v=>typeof v==='boolean')?r:null;}catch{return null;}}
function setLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i]').forEach(el=>el.textContent=copy[lang][el.dataset.i]);$('language').textContent=lang==='en'?'中文':'EN';$('language').setAttribute('aria-label',lang==='en'?'切换为中文':'Switch to English');const p=config.kind==='daily'?prior():null;$('prior-score').textContent=p?msg('First attempt: '+p.hits.filter(Boolean).length+'/5. Replays do not replace it.','本机首次成绩：'+p.hits.filter(Boolean).length+'/5。重玩不会覆盖。'):(config.kind==='practice'?msg('A shared practice challenge. Your friend gets exactly the same game.','这是一局同题练习，朋友打开链接会玩到相同题目。'):msg('Same daily challenge for everyone. Resets at 00:00 UTC.','每日同题，UTC 00:00 更新。'));if(phase==='game')renderRound();if(phase==='result')renderResult();}
$('language').onclick=()=>{lang=lang==='en'?'zh':'en';storageSet('vwb-language',lang);setLanguage();};
function show(next){phase=next;$('landing').hidden=next!=='landing';$('instructions').hidden=next!=='landing';$('game').hidden=next!=='game';$('result').hidden=next!=='result';window.scrollTo({top:0,behavior:'instant'});}
function start(c){runNumber++;config=c;rounds=makeGame(config.seed);hits=[];selected=[];index=0;show('game');renderRound();}
function practice(){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const key=bytes[0].toString(16).padStart(8,'0');start({kind:'practice',key,seed:'practice-v1-'+key});}
$('start').onclick=()=>start(configFromSearch(location.search));$('practice').onclick=practice;$('play-again').onclick=practice;
$('exit-game').onclick=()=>{runNumber++;config=configFromSearch(location.search);show('landing');setLanguage();};
const label=truth=>truth?msg('ACCEPT','通过'):msg('REJECT','不通过');
function renderRound(){
 const r=rounds[index],answered=typeof selected[index]==='number';
 $('game-code').textContent=config.kind==='daily'?config.key:msg('PRACTICE ','练习 ')+config.key;$('progress-label').textContent=(index+1)+' / 5';
 $('progress').replaceChildren(...rounds.map((_,i)=>{const n=document.createElement('span');n.className=i<hits.length?(hits[i]?'done':'miss'):i===index?'current':'';n.setAttribute('aria-label','Round '+(i+1)+': '+(i<hits.length?(hits[i]?'caught':'missed'):'pending'));return n;}));
 $('round-title').textContent=msg(['A warm-up. For you.','It says this is easy.','Now read that again.','Confidence is not evidence.','One final ego check.'][index],['热个身。说的是你。','它说这题太简单了。','再读一遍规则。','自信不是证据。','最后一次，让它认错。'][index]);
 $('rule-text').textContent=describe(r.rule,lang);$('tiles').replaceChildren();
 r.tiles.forEach((tile,i)=>{const button=document.createElement('button');button.type='button';button.className='tile';button.disabled=answered;const name=colors[lang][tile.color]+' '+shapes[lang][tile.shape]+' · '+tile.number;
 button.setAttribute('aria-label',msg('Tile ','卡片 ')+(i+1)+': '+name+'; '+msg('bot says ','机器人判断 ')+label(tile.bot));
 const id=document.createElement('span');id.className='tile-id';id.textContent='0'+(i+1);
 const shape=document.createElement('span');shape.className='shape '+tile.shape;shape.style.setProperty('--tile-color',colorValues[tile.color]);shape.textContent=tile.number;
 const nameEl=document.createElement('span');nameEl.className='tile-name';nameEl.textContent=name;const bot=document.createElement('span');bot.className='bot-label'+(tile.bot?'':' reject');bot.textContent=msg('BOT: ','它说：')+label(tile.bot);button.append(id,shape,nameEl,bot);
 if(answered){if(i===selected[index])button.classList.add(hits[index]?'caught':'missed');else if(i===r.wrong)button.classList.add('reveal');if(i===r.wrong){const truth=document.createElement('span');truth.className='truth';truth.textContent=msg('ACTUALLY: ','实际应为：')+label(accepts(r.rule,tile));button.append(truth);}}
 button.onclick=()=>answer(i);$('tiles').append(button);});
 $('next').hidden=!answered;$('next').querySelector('span').textContent=index===4?msg('GET MY REPORT','查看战绩'):copy[lang].next;$('feedback').className='feedback'+(answered?(hits[index]?' correct':' incorrect'):'');
 if(answered){$('feedback').textContent=(hits[index]?msg('Caught it. ','逮住了。'):msg('That label was right. ','你选的标签其实是对的。'))+msg('Tile '+(r.wrong+1)+' should say '+label(accepts(r.rule,r.tiles[r.wrong]))+'.','第 '+(r.wrong+1)+' 张卡应为“'+label(accepts(r.rule,r.tiles[r.wrong]))+'”。')+'\n“'+excuses[lang][index]+'”';}else $('feedback').textContent=msg('Tap the one tile the bot labelled incorrectly.','点击唯一被机器人判错的卡片。');
}
function answer(i){if(phase!=='game'||selected[index]!==undefined)return;selected[index]=i;hits[index]=i===rounds[index].wrong;renderRound();$('next').focus();}
$('next').onclick=()=>{if(selected[index]===undefined)return;if(index<4){index++;renderRound();$('rule-text').tabIndex=-1;$('rule-text').focus();}else{if(config.kind==='daily'&&!prior())storageSet('vwb-v1-'+config.key,JSON.stringify({version:VERSION,hits}));show('result');renderResult();}};
function renderResult(){const score=hits.filter(Boolean).length;$('score').textContent=score;$('result-title').textContent=msg(['The bot got away with it.','A crack in the confidence.','Two bugs. One big ego.','Human patch: installed.','An inconvenient human.','CERTIFIED EGO DEFLATOR.'][score],['这回让它蒙混过关了。','自信出现了一条裂缝。','两个错误，一个大大的自我。','人类补丁：安装成功。','一个令它头疼的人类。','机器人自信终结者。'][score]);$('result-copy').textContent=msg('You caught '+score+' of 5 mistakes. It remains 100% confident.','你揪出了 '+score+' 个错误。它的自信依然是 100%。');$('excuse-text').textContent=excuses[lang][score===5?4:score%5];$('result-grid').replaceChildren(...hits.map(v=>{const s=document.createElement('span');s.className=v?'':'fail';s.setAttribute('aria-label',v?'Caught':'Missed');return s;}));$('share-text').value=resultShare({config,hits,url:challengeURL(location.href,config)});$('share-status').textContent='';$('card-output').hidden=true;}
$('copy-score').onclick=async()=>{const version=runNumber;try{await navigator.clipboard.writeText($('share-text').value);if(version===runNumber&&phase==='result')$('share-status').textContent=msg('Copied. Send the same challenge to a friend.','已复制。可以把同题挑战发给朋友。');}catch{if(version!==runNumber||phase!=='result')return;$('share-text').focus();$('share-text').select();$('share-status').textContent=msg('Select and copy the score text below.','请复制下方选中的成绩文本。');}};
$('make-card').onclick=()=>{if(phase!=='result')return;const c=document.createElement('canvas');c.width=1200;c.height=630;const ctx=c.getContext('2d');ctx.fillStyle='#f5f2e9';ctx.fillRect(0,0,1200,630);ctx.fillStyle='#20221f';ctx.font='900 30px Arial';ctx.fillText('VERY WRONG BOT',65,75);ctx.font='13px monospace';ctx.fillStyle='#8b8179';ctx.fillText(config.kind==='daily'?config.key:'CHALLENGE '+config.key,65,111);ctx.fillStyle='#20221f';ctx.font='900 185px Arial';ctx.fillText(hits.filter(Boolean).length+'/5',59,320);ctx.font='900 34px Arial';ctx.fillText('MISTAKES CAUGHT.',65,377);ctx.font='21px Arial';ctx.fillStyle='#82718f';ctx.fillText('100% confidence. Still wrong.',65,423);hits.forEach((v,i)=>{ctx.fillStyle=v?'#b9d895':'#dda08a';ctx.fillRect(65+i*50,466,35,35);});
ctx.save();ctx.translate(873,286);ctx.rotate(-.08);ctx.fillStyle='#bfa7ec';ctx.beginPath();ctx.roundRect(-142,-111,284,210,44);ctx.fill();ctx.strokeStyle='#20221f';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#20221f';ctx.fillRect(-92,-41,58,18);ctx.fillRect(35,-52,58,24);ctx.beginPath();ctx.moveTo(-39,44);ctx.lineTo(45,32);ctx.stroke();ctx.restore();ctx.font='bold 18px Arial';ctx.fillStyle='#77608d';ctx.fillText('“MY CONFIDENCE SCORE DISAGREES.”',698,465);ctx.font='18px Arial';ctx.fillStyle='#9d9689';ctx.fillText('Your turn. Same challenge. No spoilers.',65,568);const u=new URL(challengeURL(location.href,config));ctx.font='14px monospace';ctx.fillText(u.host+u.pathname,65,594);const data=c.toDataURL('image/png');$('share-image').src=data;$('card-download').href=data;$('card-output').hidden=false;$('share-status').textContent=msg('Card ready. The text above includes the exact challenge link.','战绩卡已生成，上方文本含完整同题链接。');};
setLanguage();
