export const VERSION=1;
export const COLORS=['pink','blue','lime'],SHAPES=['circle','square','triangle'];
export function hash(text){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export function random(seed){let x=hash(String(seed));return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
const pick=(r,a)=>a[Math.floor(r()*a.length)];
export const utcDay=(date=new Date())=>date.toISOString().slice(0,10);
export function validDay(day){return typeof day==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(day)&&Number.isFinite(Date.parse(day+'T00:00:00Z'))&&new Date(day+'T00:00:00Z').toISOString().slice(0,10)===day;}
export function configFromSearch(search,today=utcDay()){const q=new URLSearchParams(search),day=q.get('d'),seed=q.get('s');if(validDay(day))return{kind:'daily',key:day,seed:'daily-v1-'+day};if(seed&&/^[a-f0-9]{8}$/.test(seed))return{kind:'practice',key:seed,seed:'practice-v1-'+seed};return{kind:'daily',key:today,seed:'daily-v1-'+today};}
export function ruleFor(rng,level){return{color:pick(rng,COLORS),shape:pick(rng,SHAPES),threshold:pick(rng,[2,3,4]),op:pick(rng,[['color','shape'],['and','threshold'],['or','xor'],['not-and','same'],['complex','xor-number']][level])};}
export function accepts(r,t){const c=t.color===r.color,s=t.shape===r.shape,n=t.number>=r.threshold;switch(r.op){case'color':return c;case'shape':return s;case'and':return c&&s;case'threshold':return s&&n;case'or':return c||s;case'xor':return c!==s;case'not-and':return!c&&s;case'same':return c===s;case'complex':return(c||s)&&t.number%2===0;case'xor-number':return(c&&s)!==n;default:throw Error('Unknown rule');}}
export function describe(r,lang='en'){const colors={pink:'粉色',blue:'蓝色',lime:'绿色'},shapes={circle:'圆形',square:'正方形',triangle:'三角形'},c=lang==='zh'?colors[r.color]:r.color.toUpperCase(),s=lang==='zh'?shapes[r.shape]:r.shape.toUpperCase(),n=r.threshold;
const en={color:`ACCEPT if it is ${c}.`,shape:`ACCEPT if it is a ${s}.`,and:`ACCEPT if it is ${c} AND a ${s}.`,threshold:`ACCEPT if it is a ${s} AND its number is at least ${n}.`,or:`ACCEPT if it is ${c} OR a ${s} (or both).`,xor:`ACCEPT if exactly ONE is true: ${c}, or a ${s}.`,'not-and':`ACCEPT if it is a ${s} AND it is NOT ${c}.`,same:`ACCEPT if BOTH are true, or BOTH are false: ${c}, a ${s}.`,complex:`ACCEPT if its number is EVEN AND it is either ${c} or a ${s} (or both).`,'xor-number':`ACCEPT if exactly ONE is true: [${c} AND a ${s}], or [number at least ${n}].`};
const zh={color:`如果是${c}，则通过。`,shape:`如果是${s}，则通过。`,and:`如果同时是${c}和${s}，则通过。`,threshold:`如果是${s}，且数字大于或等于 ${n}，则通过。`,or:`如果是${c}或${s}（包括两者都是），则通过。`,xor:`以下条件恰好一个成立才通过：${c}、${s}。`,'not-and':`如果是${s}，且不是${c}，则通过。`,same:`以下条件同时成立或同时不成立才通过：${c}、${s}。`,complex:`数字为偶数，并且是${c}或${s}（包括两者都是），则通过。`,'xor-number':`以下条件恰好一项成立才通过：[同时是${c}和${s}]、[数字大于或等于 ${n}]。`};return(lang==='zh'?zh:en)[r.op];}
export function makeGame(seed){const rng=random(seed),rounds=[];for(let level=0;level<5;level++){const rule=ruleFor(rng,level),pool=[];for(const color of COLORS)for(const shape of SHAPES)for(let number=1;number<=5;number++)pool.push({color,shape,number});const yes=pool.filter(t=>accepts(rule,t)),no=pool.filter(t=>!accepts(rule,t));const tiles=[pick(rng,yes),pick(rng,no)];while(tiles.length<6){const t=pick(rng,pool);if(!tiles.includes(t))tiles.push(t);}for(let i=tiles.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[tiles[i],tiles[j]]=[tiles[j],tiles[i]];}const wrong=Math.floor(rng()*6);rounds.push({rule,wrong,tiles:tiles.map((t,i)=>({...t,bot:i===wrong?!accepts(rule,t):accepts(rule,t)}))});}return rounds;}
export function resultShare({config,hits,url}){if(!Array.isArray(hits)||hits.length!==5||hits.some(v=>typeof v!=='boolean'))throw Error('Incomplete game');return`VERY WRONG BOT\n${config.kind==='daily'?config.key:'Challenge '+config.key} · ${hits.filter(Boolean).length}/5 caught\n${hits.map(v=>v?'🟩':'🟥').join('')}\n100% confidence. Still wrong.\nCan you catch it?\n${url}`;}
export function challengeURL(base,config){const url=new URL(base);url.search='';url.hash='';url.searchParams.set(config.kind==='daily'?'d':'s',config.key);return url.href;}
